# config.yaml
# TempCleaner 配置文件
#
# 本文件用于定义清理任务 (jobs)。
# 每个任务都包含 'paths', 'filters', 'actions' 和 'triggers'。

jobs:
  # 任务：清理下载目录中的压缩文件
  cleanup_compressed_files:
    paths:
      - '~/Downloads'
    filters:
      - pattern:
          - '**/*.zip'
          - '**/*.rar'
          - '**/*.7z'
          - '**/*.jpg'
    actions:
      # 移动到回收站以确保安全
      - trash: {}
    triggers:
      # 在系统启动时运行
      - on_startup
      # 每30分钟运行一次 (使用cron表达式)
      - schedule: "*/30 * * * *"